services:
  advisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    ports:
    - HOST_PORT:8080
    volumes:
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
version: '2'

